### ISSUE TITLE
Doesn't seem to compile with javac

### ISSUE THREAD

**Issue by lukeu** [djreiss/jasteroids3d#1]
I edited the makefile to use 'javac' instead of 'jikes', but this fails to build with these errors:

    djr\d3d\JAsteroids\JAsteroids.java:714: error: class asteroid is public, should be declared in a file named asteroid.java
    public class asteroid extends movableObject3d {
           ^
    djr\d3d\JAsteroids\JAsteroids.java:924: error: class ship is public, should be declared in a file named ship.java
    public class ship extends asteroid {
           ^
    ...

**Comment by djreiss** [comment]
Solution is to remove the "public" from all classes in JAsteroids.java, other than the JAsteroids class.
I have updated the repo to have more modern README, as well as make it compileable with `javac`. 
I added the required `MakeJarRunnable` class used by the make script.
I have also added the compiled `class` files and `jar`. WIll merge soon.

**Comment by lukeu** [comment]
Yup, works fine with my cygwin/gnumake toolchain now, thanks!

Enjoyed playing that - reminded me of my early days dabbling in 3D, before I got onto more 'mundane' programming :-)
